title: Anjali Ramchandani # your name (or website title) here
logo: "/images/headshot.png?raw=true"
description: >
  Software Engineer with four years of industry of experience
  <br><br>
  Second description
  <br><br>
  <a href="https://www.linkedin.com/in/anjaliramchandani">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
