# Site settings
name: Anjali Ramchandani
email: anjaliramchandani21@gmail.com
#canonical_url: https://edwinexemplar.com
keywords: "Software Engineer, Go, C++, JavaScript, Distributed Computing, Startups, Agile, Pair Programming"
skills: "Software Engineer"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/anjaliramchandani/
  - title: github
    url: https://github.com/Anjali-R21

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: d4af37
  primary-rgb: "212, 175, 55"
  secondary: debc5b
  secondary-dark: c9a848
  section-tout: f6e3bd



# Build settings
markdown: kramdown
permalink: pretty
